'use strict';

function buildLearningGuide() {
  return [
    '📚 Mode Belajar Arsitektur Bot',
    '',
    'Kenapa perubahan ini dilakukan:',
    '- File besar sulit dirawat, jadi bagian inti dipisah menjadi module kecil.',
    '- Retry, queue, cache, dan error guard dibuat terpusat agar bug tidak tersebar.',
    '- Provider AI dirouting secara sadar supaya bot tidak membuang request ke API yang tidak aktif.',
    '',
    'Trade-off penting:',
    '- Modularisasi membuat jumlah file bertambah, tetapi debugging dan pengembangan jadi lebih mudah.',
    '- Cache mempercepat jawaban berulang, tetapi jawaban yang sangat baru sebaiknya tetap lewat search.',
    '- Retry meningkatkan stabilitas, tetapi jumlah retry harus dibatasi agar RAM dan waktu proses tetap hemat.',
    '',
    'Risiko jika tidak diperbaiki:',
    '- Global state bisa tumbuh tanpa batas.',
    '- Error async dapat membuat proses berhenti.',
    '- JSON storage bisa rusak jika proses mati saat sedang menulis file.',
    '- Provider AI yang sedang error bisa terus dipanggil dan memperlambat bot.',
    '',
    'Alternatif solusi:',
    '- Pakai worker queue eksternal seperti BullMQ, tetapi itu lebih berat untuk Render free tier.',
    '- Pecah semua command sekaligus, tetapi risikonya besar untuk fitur lama.',
    '- Pakai database penuh, tetapi Redis + JSON fallback lebih ringan untuk tahap ini.',
    '',
    'Best practice singkat:',
    '- Pisahkan code berdasarkan tanggung jawab, bukan berdasarkan ukuran saja.',
    '- Batasi cache, memory, dan queue dengan TTL atau batas jumlah data.',
    '- Semua API eksternal perlu timeout, retry terbatas, dan logging yang jelas.',
    '',
    'Apa yang perlu kamu pahami:',
    '- Request Telegram masuk lewat webhook.',
    '- Command diproses handler, lalu state disimpan ke Redis atau JSON.',
    '- AI router memilih provider, cache mencegah panggilan ulang, circuit breaker menahan provider yang gagal.',
    '- Scheduler dan cleanup berjalan ringan agar aman saat Render restart.',
    '- Tahap 3 menambahkan pipeline: input -> safety -> context -> intent -> planner/tool/chat -> self-review -> final.',
    '- Tool hanya dijalankan jika confidence cukup. Jika ragu, bot memilih percakapan biasa.',
    '- Reflection tidak berarti bot “merenung” tanpa batas; ini filter ringan untuk mengecek klaim, duplikasi, dan risiko.',
    '- Memory dipilih secara selektif supaya prompt tidak penuh dan RAM tetap aman.',
    '- Tahap 4 menambahkan production guard: queue overload, task timeout, health diagnostics, error pattern, dan stale session cleanup.',
    '- `/system` membantu admin melihat kondisi agen, RAM, dan queue tanpa membuka log Render.',
    '- `/healthz` memberi status JSON untuk monitoring eksternal.',
    '- Tahap 5 menambahkan self-improvement loop: jawaban dinilai ringan, feedback user dicatat, lalu prompt berikutnya disesuaikan.',
    '- `/improve` membantu admin melihat quality score, reasoning score, confidence, risk, learning notes, dan failure pattern.',
    '- Mode baru `/mode refleksi`, `/mode deep`, `/mode mentor`, dan `/mode optimasi` membantu bot memilih kedalaman berpikir yang sesuai.',
    '- Bot sekarang mengikuti bahasa pengguna jika pesan memakai bahasa selain Indonesia.',
    '- Self-improvement tidak memanggil AI tambahan; ini sengaja supaya RAM, token, dan latency tetap hemat di Render free tier.',
    '- Tahap 6 menambahkan Agent Coordinator: tugas dibagi ke agent internal berdasarkan mode dan kompleksitas permintaan.',
    '- Message Bus sekarang menyimpan timeline, agent message, memory access, opinion score, conflict record, dan workflow report.',
    '- Consensus mechanism memakai confidence antar agent agar jawaban final bukan hanya output agent terakhir.',
    '- Collaborative memory menyimpan riwayat workflow kompleks secara terbatas agar bot belajar pola kerja multi-agent tanpa membengkakkan RAM.',
    '- Mode baru `/mode kolaborasi`, `/mode research-intelligence`, `/mode mentor-intelligence`, `/mode strategis`, dan `/mode system-analysis` mengaktifkan routing agent yang lebih kaya.',
    '- Tahap 7 menambahkan multimodal pipeline: attachment diklasifikasi, dicek aman, diparse, di-chunk, diberi citation, lalu digabung ke context AI.',
    '- Bot sekarang bisa menangani foto, PDF, dokumen teks, CSV/TSV/Excel, JSON, dan audio dengan fallback transcription.',
    '- Cross-modal engine menggabungkan pesan user, memory, dan evidence file agar jawaban berbasis sumber, bukan tebakan.',
    '- File cache memakai hash isi file supaya file yang sama tidak diparse berulang dan RAM/token tetap hemat.',
    '- File memory index menyimpan insight pendek, semantic tag, confidence, dan source attribution agar dokumen lama bisa dipakai ulang secara selektif.',
    '- Mode baru `/mode document-analysis`, `/mode visual-analysis`, `/mode data-understanding`, `/mode cross-modal`, dan `/mode research-file` membantu bot memilih cara analisis attachment.',
    '- Attachment direct tanpa slash command sekarang masuk ke autonomous engine; command lama `/ringkasfile` dan `/tanyafile` tetap dipertahankan.',
    '- Tahap 8 menambahkan governance layer: Policy Engine, Permission Engine, Risk Assessment, Safety Validator, Audit Logger, Approval Layer, dan Rollback Controller.',
    '- Governance memeriksa risiko sebelum tool berjalan; aksi sensitif seperti Calendar write harus dikonfirmasi dengan format `konfirmasi <id>`.',
    '- Risk assessment mengecek confidence, context trust, kata destruktif, data sensitif, attachment berisiko, dan policy tiap capability.',
    '- Audit logger menyimpan decision trail, policy violation, tool execution log, dan memory mutation log secara bounded agar tetap hemat RAM.',
    '- Rollback controller membuat snapshot kecil sebelum aksi yang mengubah state lokal, lalu bisa memulihkan jika eksekusi gagal.',
    '- Mode baru `/mode safe-mode`, `/mode governance-review`, `/mode controlled-agent`, `/mode explainability`, dan `/mode recovery` mengatur tingkat kontrol AI.',
    '',
    'Langkah berpikir ringkas:',
    '1. Cari bagian yang paling sering menyebabkan crash.',
    '2. Pisahkan fungsi pendukung yang aman tanpa mengubah command lama.',
    '3. Tambahkan batas RAM dan retry kecil.',
    '4. Tambahkan reasoning pipeline yang konservatif, bukan router agresif.',
    '5. Tambahkan guard produksi sebelum menambah fitur yang lebih kompleks.',
    '6. Tambahkan learning loop yang bounded agar sistem bisa adaptif tanpa belajar liar.',
    '7. Tambahkan kolaborasi antar agent hanya saat tugas memang butuh banyak perspektif.',
    '8. Untuk multimodal, mulai dari evidence yang bisa dibaca, beri citation, lalu jelaskan batasan jika confidence rendah.',
    '9. Untuk governance, pisahkan “boleh memahami permintaan” dari “boleh menjalankan aksi”.',
    '10. Validasi sintaks dan test lokal sebelum deploy.',
    '11. Commit perubahan per bagian agar mudah dilacak.'
  ].join('\n');
}

module.exports = {
  buildLearningGuide
};
